import Image from "next/image";
import { CTA, PageHero } from "../components/SiteChrome";
export const metadata={title:"Hizmetler"};
const items=[
{id:"yerinde",no:"01",kicker:"YERİNDE ÜRETİM",title:"Mutfağınızda, sizin operasyonunuza göre üretim.",text:"Profesyonel ekip, hijyen standartları ve proje ihtiyaçlarına uygun mutfak organizasyonuyla üretim doğrudan işletme sahasında gerçekleştirilir.",image:"https://images.pexels.com/photos/17318176/pexels-photo-17318176.jpeg?auto=compress&cs=tinysrgb&w=2200",bullets:["İşletmeye özel menü planlaması","Sahada profesyonel üretim ekibi","Günlük kalite ve hijyen takibi"]},
{id:"tasimali",no:"02",kicker:"TAŞIMALI YEMEK",title:"Merkezi üretimden planlı ve kontrollü sevkiyat.",text:"Yemekler üretim merkezinde hazırlanır, uygun taşıma koşullarında planlanan servis saatine göre sahaya ulaştırılır.",image:"https://images.pexels.com/photos/4393667/pexels-photo-4393667.jpeg?auto=compress&cs=tinysrgb&w=2200",bullets:["Planlı sevkiyat rotası","Sıcaklık ve zaman kontrolü","Vardiya saatlerine uygun teslimat"]},
{id:"paket",no:"03",kicker:"PAKET YEMEK",title:"Hijyenik paketleme, kontrollü porsiyon, pratik servis.",text:"Dağıtım ve servis kolaylığı gereken operasyonlar için porsiyon standardı korunarak paketli yemek çözümleri sunulur.",image:"https://images.pexels.com/photos/30635703/pexels-photo-30635703.jpeg?auto=compress&cs=tinysrgb&w=2200",bullets:["Standart porsiyonlama","Hijyenik ambalajlama","Hızlı dağıtıma uygun yapı"]}
];
export default function Services(){return <main><PageHero eyebrow="HİZMET MODELLERİMİZ" title="Her projeye aynı kalıp değil, doğru operasyon modeli." text="Hizmet modelini kişi sayısı, lokasyon, vardiya ve mutfak altyapısına göre birlikte belirliyoruz." image="https://images.pexels.com/photos/17318176/pexels-photo-17318176.jpeg?auto=compress&cs=tinysrgb&w=2200"/>
<section className="section wrap serviceDetailList">{items.map((x,i)=><article id={x.id} className={"serviceDetail "+(i%2?"reverse":"")} key={x.id}><div className="serviceDetailImage"><Image src={x.image} alt="" fill sizes="(max-width:900px) 100vw,50vw"/><span>{x.no}</span></div><div className="serviceDetailCopy"><p className="eyebrow red">{x.kicker}</p><h2>{x.title}</h2><p>{x.text}</p><ul>{x.bullets.map(b=><li key={b}>{b}</li>)}</ul></div></article>)}</section><CTA/></main>}